//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


public class EulerTwo{
	
	public static void main(String[] args){
		new EulerTwo().run();
	}
	
	public void run(){
		int totalSum = 0;
		int fibboNext = 1;
		int fibboCurrent = 0;
		int fibboPrev = 1;
		
		while(fibboCurrent < 4000000){
			System.out.println(fibboCurrent);
			fibboNext = fibboPrev + fibboCurrent;
			fibboPrev = fibboCurrent;
			fibboCurrent = fibboNext;
			
			if(fibboCurrent % 2 == 0){
				totalSum = totalSum + fibboCurrent;
				System.out.println("Total: " + totalSum);
			}
		}
		
	}
	
}